#!/usr/bin/python3
""" My module for testing numbers and finding the factorization """
import math
from sys import argv


def factorization_no_prime():
    """ This function finds the products of the factorization
    """


    
    for argc in range(1, len(argv)):
        with open(argv[argc], mode="r", encoding="UTF-8") as f:
            for line in f:
                number = int(line)
                if number % 2 == 0:
                    factor(number, 2)
                else:
                    max_number_to_test = math.floor(math.sqrt(number))
                    for test_num in range(3, 1 + max_number_to_test, 2):
                        if number % test_num == 0:
                            factor(number, test_num)
                            break
                            

def factor(number, test_num):
    """ Finds the values to return once a number has been found
    """


    print("{}={}*{}".format(number, (number // test_num), test_num))

factorization_no_prime()
